pipeline {
  agent any

  options {
    skipDefaultCheckout()
  }

  stages {

    stage('Checkout source code') {
      steps {
        git branch: 'master',
        url: 'https://github.com/quyquyentruong/react-for-demo.git'
        sh 'ls -la'
      }
    }

    // checkout based on configure in current Jenkins Job Build
    // stage('Checkout current code') {
    //     steps {
    //         checkout
    //     }
    // }

    stage ('Install dependencies') {
      steps {
      nodejs(nodeJSInstallationName: 'nodejs 8.9.4') {
        }
      }
    }

    stage ('Build') {
      steps {
        nodejs(nodeJSInstallationName: 'nodejs 8.9.4') {
        }
      }
    }
    
    stage ('Test') {
      steps {
      nodejs(nodeJSInstallationName: 'nodejs 8.9.4') {
        }
      }
    }
  }
}